### ISSUE TITLE
更改shadow rocket配置文件

### ISSUE THREAD

**Issue by Vaida12345** [Mornwind/GF_Region_Switcher#1]
请讲shadow rocket的配置文件中的https://raw.githubusercontent.com/Mornwind/GFCN_SwitchServer/master/Shadowrkt/gfcn_ios2gw.js
改为
/*
「少女前线」跨服（iOS 端 → 安卓官服）
By: Mornwind

README:
https://github.com/Mornwind/GFCN_SwitchServer/blob/master/README.md
*/

let url = $request.url;
let headers = $request.headers;
let body = $request.body;

url = url.replace(/gfcn-transit\.ios\.sunborngame\.com/,"gfcn-transit.gw.sunborngame.com");
headers['Host'] = 'gfcn-transit.gw.sunborngame.com';
body = body.replace(/channel=cn_appstore/,"channel=cn_mica").replace(/device=ios/,"device=adr").replace(/platformChannelId=ios/,"platformChannelId=GWGW");

$done({
	url: url,
	headers: headers,
	body: body
});
，也就是这个网站的内容。因为是github文件，不挂梯子会导致直接无法获得配置文件。
ps, shadow rocket感觉比http catcher稳定

**Comment by Mornwind** [comment]
@Vaida12345  您好，我放在GitHub上的教程和配置文件主要适用于梯子常挂的用户查阅和使用，所以这里不打算修改。
我在Gitee上有同步存放备用仓库，便于国内无梯用户访问；在博客上我也会同步更新教程，并将博客里面的链接全部替换为了Gitee的。这样正常情况下就不会有问题了（除非Gitee抽风）。
