### ISSUE TITLE
iOS-> 官安Shadowrocket 无法使用

### ISSUE THREAD

**Issue by Vaida12345** [Mornwind/GF_Region_Switcher#2]
你好：
感谢大佬这么快就发布了更新。但是依然无法使用Shadowrocket将iOS服转为安卓。麻烦您修复。感谢大佬。

**Comment by Vaida12345** [comment]
我自己尝试记录了一下少前的网络记录，发现的确唯一的区别就是http->https. 所以您的修改应该没有问题的。
这让我意识到Shadowrocket上写的是match http request, 所以也许Shadowrocket用不了了？如果是这样的话，麻烦您给我安利个新的软件。
（话说回来，小火箭是真的稳定

**Comment by Vaida12345** [comment]
找到解法了。使用http Cather, 使用您的方法，并选择decrypt https traffic, 将您的配置中的http改成https或any. 
不过此方法会导致设备安全性降低？因为所有在链接vpn时的https request都被读取了。

**Comment by Mornwind** [comment]
> 我自己尝试记录了一下少前的网络记录，发现的确唯一的区别就是http->https. 所以您的修改应该没有问题的。 这让我意识到Shadowrocket上写的是match http request, 所以也许Shadowrocket用不了了？如果是这样的话，麻烦您给我安利个新的软件。 （话说回来，小火箭是真的稳定

这是因为，我目前只来得及更新了配置文件和脚本，教程还没更新。
现在需要多做以下步骤：安装小火箭根证书，开启HTTPS解密。
这两天比较忙，教程更新还会晚点。

**Comment by Vaida12345** [comment]
感谢大佬

**Comment by Vaida12345** [comment]
小火箭也搞出来了。
开启https decryption, 签发证书，域名为
gfcn-transit.ios.sunborngame.com
